### ISSUE TITLE
FFI related paper cuts in driver ↔ lint-crate communication

### ISSUE THREAD

**Issue by xFrednet** [rust-linting/rust-linting#37]
When I created the prototype, I hacked together a basic *driver ↔ lint-crate* communication. After reworking the communication and learning more about FFI stuff, it turns out that the current implementation is unsound. This is a collection of all issues that need to be fixed:

* [ ] API types use non-`#[repr(C)]` types. These need to be replaced with FFI safe types or at least safely be transferred over the FFI boarder
    * Example: Slices, `Option<>`, `&str`
* [ ] Types from the FFI module should be hidden, as they are not part of the stable ABI
* [ ] Remove `&dyn Trait` pointers from the API
* [ ] Make sure that every exchanged type has `#[repr(C)]` (#6)

Note: We can change `#[repr(C)]` to a different ABI as long as it's stable like C

**Comment by xFrednet** [comment]
I'm currently slowly working on these, while designing the AST. The last few PRs already made some good progress, like adding the FFI module to `linter_api`

**Comment by xFrednet** [comment]
A lot of progress on this has been made in #54 as it removes a lot of `dyn` and traits. The API is not totally FFI safe, but has a good baseline by my estimation
